### ISSUE TITLE
JB Post Intelligencer Volume 1 Issue 1 April 1, 1998 + Sumo PR Pic

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#104]
The Newsletter of The  Group That doesn't Exist,...Hahaha!

I've been doing a little sorting and I found this hiding behind some old pictures!  I believe Pat sent this to me sometime in 1998 about a year after the 1st Pat & Max reunion at The Great American Music Hall in 1997. 

![JB Post Intelligencer](https://user-images.githubusercontent.com/93959968/185983641-64b03177-4c06-4563-be33-f7ee41f1a626.jpg)

 Pat also included a Sumosonic PR photo with a cassette complete and mixed copy of the new Sumosonic - This Is Sumo.  

![Sumosonic pr photo](https://user-images.githubusercontent.com/93959968/185985060-8a559030-e62b-421a-bd7a-2e84f4b35d5d.jpeg)

**Comment by xpollen8** [comment]
Thanks. I also have a copy and didn't think to scan it: http://jazzbutcher.com/press/post-intelligencer.html

Hey - yay - a different Sumo shot

**Comment by Bigquestionsinc** [comment]
Ha,Yes! That's it!! I found a few other things I'll scan and upload soon as well!

    On Monday, August 22, 2022 at 11:05:20 AM PDT, xpollen8 ***@***.***> wrote:  
 
 


Thanks. I also have a copy and didn't think to scan it: http://jazzbutcher.com/press/post-intelligencer.html

Hey - yay - a different Sumo shot

**Comment by presto211** [comment]
Sorry to spoil the lurking and pipe in here, gentlemen, but I thought I might shed a little light on the Maureen Tucker end of things from that newsletter if you’re interested. The girl we had enlisted to play drums for them in ATL (Ani Cordero) was in a band with and good friends with a guy who had done some studio work with Mo. Totally unprompted, she suggested that it might be possible to get her to sit in as she lived close by, in Covington or some place. I don’t even know if Ani knew of Pat’s love for the VU! In any case, it never materialized, and I felt so bad for Pat because I know he would’ve really liked that. I didn’t realize that David J was also a possible guest.

~KBJr

============
About Me
http://about.me/berman <http://about.me/berman>

**Comment by xpollen8** [comment]
Scan has been to the press page: http://jazzbutcher.com/press/post-intelligencer.html

@presto211 If you visit that page and add your Maureen story, I'd appreciate it (cleaner than me cutting-pasting from here)

**Comment by xpollen8** [comment]
Also added: http://jazzbutcher.com/press/19980401_Sumosonic_Promo_Trio.html
