### ISSUE TITLE
JBC 'Masters Of Budvar' Hamburg 2005

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#108]
https://www.dropbox.com/scl/fo/7c67xc2g9nkt2nrvny2ju/h?dl=0&rlkey=5jvpi5y56zxl1ein6n8i8bchv

THE JAZZ BUTCHER CONSPIRACY

Masters Of Budvar October 27, 2005
KIR 
Barnestrasse 16
22765 Hamburg
Tel 040 / 43 80 41
 
DISC 1
Solo Sets
Tracks 1-1 to 1-4 Pat Fish  
Tracks 1-5 to 1-8 Peter Crouch (With Pat also on Guitar)
Tracks 1-9 to 1-11 Owen Jones (With Max on Guitar)
Tracks 1-12 to 1-14 Max Eider (With Pat - Drums on 'My Other Life')
Backing vocals Kathie McGinty and ? (I’ll have to ask Brian Kelly)

DISC 2
Tracks 2-1 to 2-7 Joe Woolley
Tracks 3-1 to 3-17 The Jazz Butcher Conspiracy (Full Band)

This comes from a double CD Bootleg given to Brian Kelly by Owen Jones
I will ask Brian we can get the full AIFF/WAV transfer.

![The Jazz Butcher Conspiracy Soul Revue](https://user-images.githubusercontent.com/93959968/204376400-7f86afa3-1330-4e1a-8320-26cf8cec105d.png)

**Comment by presto211** [comment]
Here’s an image of the newspaper ad for the referenced show at the Town & Country Club that my buddy over at the askingtreee.com <http://askingtreee.com/> (a Robyn Hitchcock site) sent me, in case you want it for that gig page. Hope all’re well!



~KBJr

============
About Me
http://about.me/berman <http://about.me/berman>

**Comment by xpollen8** [comment]
Done!

https://jazzbutcher.com/gigs/2005/Oct27.html

**Comment by xpollen8** [comment]
> Here’s an image of the newspaper ad for the referenced show at the Town & Country Club that my buddy over at the askingtreee.com <http://askingtreee.com/> (a Robyn Hitchcock site) sent me, in case you want it for that gig page. Hope all’re well! ~KBJr ============ About Me http://about.me/berman <http://about.me/berman>

Hey Knight!  Can you clarify what your message is about?

**Comment by presto211** [comment]
Hey David! I’m trying to remember, so I found the January 2023 Messenger thread about it all from my friend Marcus Slade who puts things together for a Robyn Hitchcock site called The Asking Tree. I’m pasting it in below in hopes it will provide clarity:

[BEGIN MISSIVE]
MARCUS SLADE: Hi Knight. I wonder if you could check something with the Jazz Butcher fans, or maybe you know yourself? In the Asking Tree we have this entry https://askingtree.com/gigs/378 for a show at the Whisky in LA on 9/4/91 and it says Pat Fish opened. But we also have an entry for another Whisky show on 4/9/91 https://askingtree.com/gigs/1238 and we are thinking there could have been an issue with transposing dates between USA and UK format. I was wondering if the Pat Fish/Jazz Butcher fandom knows about this show and can confirm if it happened on April 9th or September 4th? Based on surrounding dates it is possible that Robyn would have been in LA at both times, so it is not obvious which is correct. Thanks.

KBJ: Hi Marcus! According to the Butcher site, Pat didn’t play many gigs in 1991…but one of them happened to be at the Whiskey on Sept 4th! https://jazzbutcher.com/gigs/1991… I’m going to leave a comment to the info on the Butcher site with a link to the Asking Tree page (if that’s all right with you) to reflect that it was an opening gig for Robyn.

MS: Thanks for this.  Link away! Any traffic to the site is appreciated. You might want to link to this gig too where the JB opened. We have a gig add that mentions them https://askingtree.com/gigs/246 <https://askingtree.com/gigs/246> I can send you the image file for that add so you don't have to save from our site. Give me a minute…




KBJ: Just took a closer look at each of those gigs, and I neglected to see the little “Details” tab that reveals that these were shows with Robyn. I’ll still put a comment on each one with a link to the Asking Tree pages, as well as drop that image for the 1988 gig in, if attachments to comments are possible (and if the webmaster allows outside links within comments)…

[END MISSIVE]

Back to the present, hope that makes some sense and is useful rather than redundant!

~KBJr

============
About Me
http://about.me/berman <http://about.me/berman>
