### ISSUE TITLE
1985-04-25 -Melkweg, Amsterdam show (Replace My YouTube Upload)

### ISSUE THREAD

**Issue by wnerini** [xpollen8/jazzbutcher.com#70]
RIP original tape from Pat, upload with setlist and cassette images. 

**NOTE: To replace my YouTube upload of the show.** Avoids adverts. 😄

**Comment by wnerini** [comment]
Cassette/label images:

![IMG_20211106_095251844](https://user-images.githubusercontent.com/64444368/145152440-0a7eeb42-e7fc-498b-8cb6-f0b8870d0cb1.jpg
![IMG_20211106_095227817sm](https://user-images.githubusercontent.com/64444368/145152454-40288a80-860b-47fd-9658-232eadf123b1.jpg)
)

**Comment by wnerini** [comment]
Uploaded. Should be better quality than my cheesoid YouTube upload and have no ads.

**Comment by xpollen8** [comment]
Ah... since that was signed (Pat '97) was that one of the original "Pat sends David a bunch of stuff to auction off" batches..? 

#   OLD     <td valign=top>T002</td>
#   OLD     <td valign=top>$55</td>
#   OLD     <td valign=top>${itemSold}<br>
#   OLD     wnerini @
#   OLD     </td>
#   OLD     <td valign=top><a href="${jbc_gigs}/1985/Apr25.html"><b>Melkweg, Amsterdam : 25Apr85</b></a>


Why... yes, yes it is!  Pretty sure I duped that to DAT back then, too.

**Comment by wnerini** [comment]
> Ah... since that was signed (Pat '97) was that one of the original "Pat sends David a bunch of stuff to auction off" batches..?
> 
> #   OLD     T002
> #   OLD     $55
> #   OLD     ${itemSold}
> 
> #   OLD     wnerini @
> #   OLD     
> #   OLD     [Melkweg, Amsterdam : 25Apr85](${jbc_gigs}/1985/Apr25.html)
> Why... yes, yes it is! Pretty sure I duped that to DAT back then, too.

Yessir, that's me. :) 

Also still have the poster for the Onkel Po show.

**Comment by xpollen8** [comment]
Added: http://jazzbutcher.com/gigs/1985/Apr25.html

**Comment by xpollen8** [comment]
btw @wnerini - I see that you also won this one, which I've already digitized, so if it was on your radar, I've got it covered...

19891218_JBC_TipitinasNewOrleans.wav

**Comment by xpollen8** [comment]
deployed: http://jazzbutcher.com/gigs/1985/Apr25.html
